import './globals.css';

import { bodyFont } from './config/fonts';
import 'primereact/resources/themes/lara-light-blue/theme.css';


import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Total Seal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
    
      <body className={bodyFont.className}>
        {children}
      </body>
    </html>
  );
}
