import './globals.css';

import { bodyFont } from './config/fonts';
import 'primereact/resources/themes/lara-light-blue/theme.css';


import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Total Seal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              const style = document.createElement('style')
              style.innerHTML = '@layer tailwind-base, primereact, tailwind-utilities;'
              style.setAttribute('type', 'text/css')
              document.querySelector('head').prepend(style)
            `,
          }}
        />
      </head>
      <body className={bodyFont.className}>
        {children}
      </body>
    </html>
  );
}
