name: Issue transitionated to testing on PR approval
'on':
    pull_request_review:
      types: [submitted]

jobs:
  issue_transitionated_to_testing_on_pr_approval:
    runs-on: ubuntu-latest
    steps:

      - name: Extract PR Number
        id: pr
        run: echo "::set-output name=number::${{ github.event.pull_request.number }}"

      - name: Extract JIRA Issue ID
        id: jira_issue_id
        run: |
          FULL_STRING="${{ github.event.pull_request.head.ref }}"
          JIRAISSUEID=$(echo $FULL_STRING | cut -d'-' -f1,2)
          echo "JIRAISSUEID=$JIRAISSUEID" >> $GITHUB_ENV

      - name: Update JIRA Issue
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        run: |
          PR_NUMBER=${{ steps.pr.outputs.number }}
          # Extract JIRA issue key from PR title or branch name
          JIRA_ISSUE_KEY=${{env.JIRAISSUEID}}
          # If JIRA issue key is found
          if [ ! -z "$JIRA_ISSUE_KEY" ]; then
            # JIRA API call to update the issue
            curl --http1.1 -X PUT \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $(echo -n $JIRA_USER_EMAIL:$JIRA_API_TOKEN | base64)" \
            ${{vars.JIRA_BASE_URL}}/rest/api/2/issue/${{ env.JIRAISSUEID }} \
            -d '{
              "update": {
                "customfield_10058": "$PR_NUMBER"
              }
            }'
          fi

      - name: Check if PR is ready
        run: |
            PR_NUMBER=${{ steps.pr.outputs.number }}
            if [[ "${{ github.event.review.state }}" == "approved" ]]; then
              echo "Pull request is ready to be merged => Transitioning JIRA issue ${{ env.JIRAISSUEID }} to Testing."
              # Transition the JIRA issue.
              TRANSITION_ID=$(curl -X GET -H "Content-Type: application/json" \
                  -u ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
                  ${{vars.JIRA_BASE_URL}}/rest/api/3/issue/${{ env.JIRAISSUEID }}/transitions | jq -r '.transitions[] | select(.name=="Functional Testing") | .id')
              echo "Transition ID: $TRANSITION_ID"
              curl -X POST -H "Content-Type: application/json" \
                  -d '{"transition":{"id":"'$TRANSITION_ID'"}}' \
                  -u ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
                  ${{vars.JIRA_BASE_URL}}/rest/api/3/issue/${{ env.JIRAISSUEID }}/transitions
            else
                echo "Pull request is not ready to be merged."
            fi
